### ISSUE TITLE
Is there a way of use it with DETR ?

### ISSUE THREAD

**Issue by ver0z** [yhlleo/VTs-Drloc#4]
Is it feasible to use your approach with the DETR ?

**Comment by yhlleo** [comment]
@ver0z , it's an interesting question. In my mind, I think it's feasible to apply our self-supervised loss in the output feature sequence of the encoding module in DETR. Enhancing the spatial information in the feature sequence, could be useful for object detection tasks.

**Comment by ver0z** [comment]
Yes, that's what I was thinking, could be very useful. I'm working with DETR and I will try to join/stack these two.

**Comment by yhlleo** [comment]
Awesome! I'm looking forward to hearing from your experimental results.
