### ISSUE TITLE
Imagenet-100 split

### ISSUE THREAD

**Issue by xiangyu8** [yhlleo/VTs-Drloc#5]
Thanks for your amazing work! 
I also want to train with imagenet-100 using the subset in the file /scripts/imagenet-100.lst. But I didn't find its train/val split. May I know your splits or split reference?

**Comment by yhlleo** [comment]
Hi @xiangyu8 , the category list of ImageNet-100 is provided [here](https://github.com/yhlleo/VTs-Drloc/blob/master/scripts/imagenet-100.lst). The train and val images are directly from the original ImageNet-1K dataset. We also upload the train/val list [here](https://drive.google.com/drive/folders/1s8aHXp_clmCDqS0qXHWfdmsdM3X7sxuL?usp=sharing).

**Comment by xiangyu8** [comment]
Got it! Thank you so much!
